package com.example.healthvault.dto;

import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserRegistrationDTO {

//    private String username;
    private String email;
    private String password;

    // Getters and Setters (generated by Lombok)
}
