version: "3.9"  # Use a recent version of the Docker Compose file format

services:
  health-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: health
    ports:
      - "3306:3306"
